stages:
  - pr_agent

Improve-MR:
    stage: pr_agent
    tags:
        - linux
    image:
        name: codiumai/pr-agent:latest
        entrypoint: [""]
    script:
        - echo "Running PR Agent action step"
        - export MR_URL="$CI_MERGE_REQUEST_PROJECT_URL/merge_requests/$CI_MERGE_REQUEST_IID"
        - echo "MR_URL=$MR_URL"
        - export gitlab__url=$CI_SERVER_PROTOCOL://$CI_SERVER_FQDN
        - export gitlab__PERSONAL_ACCESS_TOKEN=$GITLAB_PERSONAL_ACCESS_TOKEN
        - export config__git_provider="gitlab"
        - export openai__key=$OPENAI_KEY
        - python -m pr_agent.cli --pr_url="$MR_URL" improve
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    when: manual

Describe-MR:
    stage: pr_agent
    tags:
        - linux
    image:
        name: codiumai/pr-agent:latest
        entrypoint: [""]
    script:
        - echo "Running PR Agent action step"
        - export MR_URL="$CI_MERGE_REQUEST_PROJECT_URL/merge_requests/$CI_MERGE_REQUEST_IID"
        - echo "MR_URL=$MR_URL"
        - export gitlab__url=$CI_SERVER_PROTOCOL://$CI_SERVER_FQDN
        - export gitlab__PERSONAL_ACCESS_TOKEN=$GITLAB_PERSONAL_ACCESS_TOKEN
        - export config__git_provider="gitlab"
        - export openai__key=$OPENAI_KEY
        - python -m pr_agent.cli --pr_url="$MR_URL" describe
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    when: manual

Review-MR:
    stage: pr_agent
    tags:
        - linux
    image:
        name: codiumai/pr-agent:latest
        entrypoint: [""]
    script:
        - echo "Running PR Agent action step"
        - export MR_URL="$CI_MERGE_REQUEST_PROJECT_URL/merge_requests/$CI_MERGE_REQUEST_IID"
        - echo "MR_URL=$MR_URL"
        - export gitlab__url=$CI_SERVER_PROTOCOL://$CI_SERVER_FQDN
        - export gitlab__PERSONAL_ACCESS_TOKEN=$GITLAB_PERSONAL_ACCESS_TOKEN
        - export config__git_provider="gitlab"
        - export openai__key=$OPENAI_KEY
        - python -m pr_agent.cli --pr_url="$MR_URL" review
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    when: manual
