# Maintainer: Chieh

version: "3.8"
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${PWD}/pg-data:/var/lib/postgresql/data
      - ${PWD}/sql_script:/root/test
    container_name: database
    tty: true
    ports:
     - "5432:5432"
    restart: unless-stopped