version: "3.7"
services:
  chieh-proxy:
    image: chieh:proxy-v1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chieh-proxy
    ports:
      - 8501:8501
    restart: always