version: '3'
services:
  fastapi-app:
    build:
      context: .
    volumes:
      - ./server:/app
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8123"]
    ports:
      - "8123:8123"