version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      kafka:
        ipv4_address: 173.38.0.10

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://173.38.0.2:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://173.38.0.2:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_BOOTSTRAP.SERVERS: 'kafka:29091'
      KAFKA_BROKER_ID: 1
    networks:
      kafka:
        ipv4_address: 173.38.0.2

  WebServer:
    image: chiehpower/kafka_practice:v0.1
    build: .
    tty: true
    volumes:
      - ${PWD}:/kafka:rw
    container_name: WebServer
    command: bash -c "bash"
    networks:
      kafka:
        ipv4_address: 173.38.0.3

  # control-center:
  #   image: confluentinc/cp-enterprise-control-center:5.3.1
  #   container_name: control-center
  #   depends_on:
  #     - zookeeper
  #     - kafka
  #   ports:
  #     - "9021:9021"
  #   environment:
  #     CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
  #     CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  #     CONTROL_CENTER_CONNECT_CLUSTER: 'connect:8083'
  #     CONTROL_CENTER_KSQL_URL: "http://ksql-server:8088"
  #     CONTROL_CENTER_KSQL_ADVERTISED_URL: "http://localhost:8088"
  #     CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  #     CONTROL_CENTER_REPLICATION_FACTOR: 1
  #     CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
  #     CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
  #     CONFLUENT_METRICS_TOPIC_REPLICATION: 1
  #     PORT: 9021
  #   networks:
  #     kafka:
  #       ipv4_address: 173.38.0.4

networks:
  kafka:
    driver: bridge
    ipam:
      config:
        - subnet: 173.38.0.0/16
